set names utf8;
del_idx('databaseAddIndex','fx_city_region','cr_name');
ALTER TABLE `fx_city_region` ADD KEY `cr_name`( `cr_name` )USING BTREE ;
del_idx('databaseAddIndex','fx_goods','g_is_combination_goods');
ALTER TABLE `fx_goods` ADD KEY `g_is_combination_goods`( `g_is_combination_goods` )USING BTREE ;
del_idx('databaseAddIndex','fx_orders','o_create_time');
ALTER TABLE `fx_orders` ADD KEY `o_create_time`( `o_create_time` )USING BTREE ;
del_idx('databaseAddIndex','fx_orders_items','oi_create_time');
ALTER TABLE `fx_orders_items` ADD KEY `oi_create_time`( `oi_create_time` )USING BTREE ;
del_idx('databaseAddIndex','fx_orders_items','oi_ship_status');
ALTER TABLE `fx_orders_items` ADD KEY `oi_ship_status`( `oi_ship_status` )USING BTREE ;
del_idx('databaseAddIndex','fx_orders_items','oi_refund_status');
ALTER TABLE `fx_orders_items` ADD KEY `oi_refund_status`( `oi_refund_status` )USING BTREE ;
del_idx('databaseAddIndex','fx_orders_items','oi_type');
ALTER TABLE `fx_orders_items` ADD KEY `oi_type`( `oi_type` )USING BTREE ;
del_idx('databaseAddIndex','fx_thd_goods','thd_goods_sn');
ALTER TABLE `fx_thd_goods` ADD KEY `thd_goods_sn`( `thd_goods_sn` );
del_idx('databaseAddIndex','fx_payment_cfg','pc_pay_type');
ALTER TABLE `fx_payment_cfg` ADD KEY `pc_pay_type` (`pc_pay_type`);
del_idx('databaseAddIndex','fx_payment_cfg','pc_abbreviation');
ALTER TABLE `fx_payment_cfg` ADD KEY `pc_abbreviation` (`pc_abbreviation`);
del_idx('databaseAddIndex','fx_payment_cfg','pc_source');
ALTER TABLE `fx_payment_cfg` ADD KEY `pc_source` (`pc_source`);
del_idx('databaseAddIndex','fx_thd_goods','thd_goods_id');
ALTER TABLE `fx_thd_goods` ADD KEY `thd_goods_id` (`thd_goods_id`);
del_idx('databaseAddIndex','fx_thd_goods','ts_id');
ALTER TABLE `fx_thd_goods` ADD KEY `ts_id` (`ts_id`);
del_idx('databaseAddIndex','fx_thd_goods','thd_source');
ALTER TABLE `fx_thd_goods` ADD KEY `thd_source` (`thd_source`);
del_idx('databaseAddIndex','fx_goods_products','thd_indentify');
ALTER TABLE `fx_goods_products` ADD KEY `thd_indentify` (`thd_indentify`);
del_idx('databaseAddIndex','fx_goods_products','thd_pdtid');
ALTER TABLE `fx_goods_products` ADD KEY `thd_pdtid` (`thd_pdtid`);
del_idx('databaseAddIndex','fx_goods_type','gt_name');
ALTER TABLE `fx_goods_type` ADD KEY `gt_name` (`gt_name`);
del_idx('databaseAddIndex','fx_goods_category','gc_name');
ALTER TABLE `fx_goods_category` ADD KEY `gc_name` (`gc_name`);
del_idx('databaseAddIndex','fx_goods_spec','thd_gpid');
ALTER TABLE `fx_goods_spec` ADD KEY `thd_gpid` (`thd_gpid`);
del_idx('databaseAddIndex','fx_top_itemprops','pid');
ALTER TABLE `fx_top_itemprops` ADD KEY `pid` (`pid`);
del_idx('databaseAddIndex','fx_goods_spec_detail','thd_indentify');
ALTER TABLE `fx_goods_spec_detail` ADD KEY `thd_indentify` (`thd_indentify`);
del_idx('databaseAddIndex','fx_goods_spec_detail','thd_gpid');
ALTER TABLE `fx_goods_spec_detail` ADD KEY `thd_gpid` (`thd_gpid`);
del_idx('databaseAddIndex','fx_goods_spec_detail','thd_gpvid');
ALTER TABLE `fx_goods_spec_detail` ADD KEY `thd_gpvid` (`thd_gpvid`);
del_idx('databaseAddIndex','fx_orders','o_receiver_name');
ALTER TABLE `fx_orders` ADD KEY `o_receiver_name` (`o_receiver_name`);
del_idx('databaseAddIndex','fx_orders','o_receiver_mobile');
ALTER TABLE `fx_orders` ADD KEY `o_receiver_mobile` (`o_receiver_mobile`);
del_idx('databaseAddIndex','fx_orders','admin_id');
ALTER TABLE `fx_orders` ADD KEY `admin_id` (`admin_id`);
INSERT INTO `fx_payment_cfg` (`pc_id`, `pc_custom_name`, `pc_pay_type`, `pc_abbreviation`, `pc_config`, `pc_fee`, `pc_memo`, `pc_last_modify`, `erp_payment_id`, `pc_status`, `pc_trd`, `pc_position`) VALUES ('12', '银联在线v5.0.0', 'chinapayv5', 'CHINAPAYV5', '', '0.000', '银联在线支付(全渠道商户)', '2015-01-23 06:28:04', '0', '0', '1', '6');
INSERT INTO `fx_payment_cfg` (`pc_id`,`pc_custom_name`,`pc_pay_type`,`pc_abbreviation`,`pc_memo`,`pc_status`,`pc_trd`,`pc_position`) VALUES ('13','微信支付','weixin','WEIXIN','此支付方式为商城微信支付(PC端扫码支付、手机端公众号支付)','0','1','13');
ALTER TABLE `fx_orders_refunds` MODIFY COLUMN `or_refund_type` tinyint(3) NOT NULL DEFAULT '1' COMMENT '1,退款;2,退货;3,退运费';
ALTER TABLE `fx_logistic_corp` ADD COLUMN `lc_jd_name` varchar(50) NOT NULL COMMENT '京东物流公司名称';
