set names utf8;
DROP TABLE IF EXISTS `fx_role_node`;
CREATE TABLE `fx_role_node` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '节点ID',
  `action` varchar(60) NOT NULL DEFAULT '' COMMENT '节点控制器',
  `action_name` varchar(60) NOT NULL DEFAULT '' COMMENT '节点控制器名称',
  `module` varchar(60) NOT NULL DEFAULT '' COMMENT '节点模型',
  `module_name` varchar(60) NOT NULL DEFAULT '' COMMENT '节点模型名称',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '节点是否可用:0为禁用,1为禁用',
  `sort` smallint(6) NOT NULL DEFAULT '0' COMMENT '节点排序',
  `auth_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '授权模式：1:模块授权(module) 2:操作授权(action) 0:节点授权(node)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `action_module` (`action`,`module`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=250 DEFAULT CHARSET=utf8 COMMENT='节点表';
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Home', '官网模板', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSetting', '查看官网基本信息设置', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSet', '更新官网基本信息', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageClose', '暂停营业公告', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSetClose', '添加/修改暂停营业公告', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageRegister', '注册协议', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddRegister', '处理注册协议', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageTpl', '官网模板管理', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageTopAd', '首页头部广告图片管理', 'Home', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Notice', '网站公告', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '公告列表', 'Notice', '网站公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '发布公告', 'Notice', '网站公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '处理添加公告', 'Notice', '网站公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑公告', 'Notice', '网站公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新公告', 'Notice', '网站公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除公告', 'Notice', '网站公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Announcement', '违规公告', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '违规公告列表', 'Announcement', '违规公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增违规公告', 'Announcement', '违规公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加违规公告', 'Announcement', '违规公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑违规公告', 'Announcement', '违规公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新违规公告', 'Announcement', '违规公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除违规公告', 'Announcement', '违规公告', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Article', '官网资讯', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '官网资讯列表', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增官网资讯', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加官网资讯', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑资讯', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新资讯', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除资讯', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageListCate', '官网资讯分类', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAddCate', '新增资讯分类', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddCate', '添加资讯分类', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEditCate', '编辑资讯分类', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditCate', '更新资讯分类', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelCate', '删除资讯分类', 'Article', '官网资讯', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Seo', '搜索引擎优化设置', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', 'SEO列表', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑SEO', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新SEO信息', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageMap', '站点地图设置展示', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doMapSave', '保存站点地图生成的配置信息', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doMapRefresh', '刷新站点地图缓存', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageCount', '统计脚本设置', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doCount', '保存第三方统计脚本', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageCach', '查看缓存设置', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'cachAdd', '执行保存缓存设置', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'deleteCacheDir', '删除缓存数据', 'Seo', '搜索引擎优化设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Links', '友情链接', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '友情链接列表', 'Links', '友情链接', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增友情链接', 'Links', '友情链接', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加友情链接', 'Links', '友情链接', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑友情链接', 'Links', '友情链接', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新友情链接', 'Links', '友情链接', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除友情链接', 'Links', '友情链接', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Online', '在线客服', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '在线客服列表', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增在线客服', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加在线客服', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑在线客服', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新在线客服', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除在线客服', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageListCate', '在线客服分类', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEditCate', '编辑在线客服分类', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAddCate', '新增在线客服分类', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddCate', '添加在线客服分类', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditCate', '更新在线客服分类', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelCate', '删除在线客服分类', 'Online', '在线客服', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Guestbook', '商品评论', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageProductsList', '商品评论列表', 'Guestbook', '商品评论', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageProductsSetting', '商品评论设置', 'Guestbook', '商品评论', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doPageProductsSetting', '更新商品评论设置', 'Guestbook', '商品评论', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doProductsDel', '商品评论删除', 'Guestbook', '商品评论', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doProductsAudit', '商品评论审核', 'Guestbook', '商品评论', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setGoodComment', '点击回复评论', 'Guestbook', '商品评论', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doGoodsComment', '回复评论', 'Guestbook', '商品评论', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Message', '站内信', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageMailBox', '站内信列表', 'Message', '站内信', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSend', '新增站内信', 'Message', '站内信', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加站内信', 'Message', '站内信', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageRead', '查看站内信', 'Message', '站内信', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageReply', '回复站内信', 'Message', '站内信', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doReply', '处理回复站内信', 'Message', '站内信', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除站内信', 'Message', '站内信', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Suggestions', '投诉建议', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '投诉建议列表', 'Suggestions', '投诉建议', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageDetail', '投诉建议详情', 'Suggestions', '投诉建议', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doIshandle', '处理投诉建议', 'Suggestions', '投诉建议', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Nav', '自定义导航栏', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '自定义导航列表', 'Nav', '自定义导航栏', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增自定义导航', 'Nav', '自定义导航栏', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑自定义导航', 'Nav', '自定义导航栏', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新自定义导航', 'Nav', '自定义导航栏', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除自定义导航', 'Nav', '自定义导航栏', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Operation', '日志操作记录设置', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '后台操作记录列表 ', 'Operation', '日志操作记录设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Products', '商品管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '商品列表', 'Products', '商品管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doGoodsisDel', '删除商品', 'Products', '商品管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageDetail', '查看商品详情', 'Products', '商品管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setGoodPoint', '设置商品积分', 'Products', '商品管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setItemSaleNumbers', '修改商品销量', 'Products', '商品管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doGoodsOnSale', '商品上下架', 'Products', '商品管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'detail', '商品预览', 'Products', '商品管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Goods', '商品管理详情', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'goodsAdd', '新增商品页面', 'Goods', '商品管理详情', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doGoodsAdd', '添加商品', 'Goods', '商品管理详情', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'goodsEdit', '商品编辑页面', 'Goods', '商品管理详情', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doGoodsEdit', '修改商品', 'Goods', '商品管理详情', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'ajaxSetGoodsFlag', '商品标记状态翻转(是否是新品、热销)', 'Goods', '商品管理详情', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'combinationGoodsList', '组合商品列表 ', 'Goods', '组合商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addCombinationGoodPage', '新增组合商品', 'Goods', '组合商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'editCombinationGoodsPage', '编辑组合商品', 'Goods', '组合商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'deleteCombiantionGoods', '删除组合商品', 'Goods', '组合商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'combinationPropertyGoodsList', '规格组合商品列表', 'Goods', '组合规格商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addCombinationPropertyGoodsPage', '添加规格组合商品', 'Goods', '组合规格商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'editCombinationPropertyGoodsPage', '规格组合商品详情', 'Goods', '组合规格商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'editCombinationPropertyGoods', '修改组合规格商品', 'Goods', '组合规格商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'ajaxDelCombinationPropertyGoods', '删除组合规格商品', 'Goods', '组合规格商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'enableCombinationPropertyGoods', '启用（停用）规格组合商品', 'Goods', '组合规格商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'configIndustrySpec', '行业属性配置', 'Goods', '组合商品', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Stock', '库存管理', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '库存调整单', 'Stock', '库存管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageDetail', '库存调整单明细', 'Stock', '库存管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增库存调整单', 'Stock', '库存管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '库存设置', 'Stock', '库存管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'GoodsCategory', '商品分类管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '商品分类列表 ', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '分类编辑 ', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addCategory', '添加商品分类 ', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageDisplay', '更新分类显示状态(显示或不显示) ', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '保存分类 ', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新分类 ', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除分类 ', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addCategoryPromotion', '类目促销区设置', 'GoodsCategory', '商品分类管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'GoodsType', '商品类型管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '商品类型列表 ', 'GoodsType', '商品类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addGoodsType', '类型添加 ', 'GoodsType', '商品类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'eidtGoodsType', '类型编辑 ', 'GoodsType', '商品类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelTypeDetail', '类型删除 ', 'GoodsType', '商品类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelType', '类型批量删除 ', 'GoodsType', '商品类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEidtType', '类型更新 ', 'GoodsType', '商品类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddType', '类型保存 ', 'GoodsType', '商品类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'GoodsProperty', '商品属性管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'specListPage', '商品属性列表 ', 'GoodsProperty', '商品属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'specEditPage', '编辑属性 ', 'GoodsProperty', '商品属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addSpecPage', '属性添加 ', 'GoodsProperty', '商品属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelSpec', '删除属性 ', 'GoodsProperty', '商品属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditSpec', '更新属性 ', 'GoodsProperty', '商品属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddSpec', '保存属性 ', 'GoodsProperty', '商品属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doPropertyIsSearch', '启用/停用属性 ', 'GoodsProperty', '商品属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'freeCollocationList', '自由推荐列表', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addFreeCollocationPage', '新增自由推荐', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addFreeCollocation', '保存自由推荐', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'enableFreeCollocation', '启用/关闭自由推荐', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'editFreeCollocationPage', '启用/编辑自由推荐', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'editFreeCollocation', '更新自由推荐', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'ajaxDelFreeCollocation', '删除自由推荐', 'GoodsFreeCollocation', '商品自由推荐管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'GoodsBrand', '商品品牌管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '品牌列表', 'GoodsBrand', '商品品牌管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addBrand', '新增商品品牌', 'GoodsBrand', '商品品牌管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加商品品牌', 'GoodsBrand', '商品品牌管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑商品品牌', 'GoodsBrand', '商品品牌管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新商品品牌', 'GoodsBrand', '商品品牌管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除商品品牌', 'GoodsBrand', '商品品牌管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doStatus', '品牌启用/停用', 'GoodsBrand', '商品品牌管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'GoodsGroup', '商品分组管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '商品分组列表', 'GoodsGroup', '商品分组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addGroup', '新增商品分组', 'GoodsGroup', '商品分组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addGoodsToGroup', '添加商品到分组', 'GoodsGroup', '商品分组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑商品分组', 'GoodsGroup', '商品分组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'removeGoodsToGroup', '移出分组的商品', 'GoodsGroup', '商品分组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除商品分组', 'GoodsGroup', '商品分组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Orders', '订单管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '订单列表', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageDetails', '订单详情', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'ajaxInvalidOrder', '订单作废', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageWaitPayOrdersList', '待付款订单', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageWaitDeliverOrdersList', '待发货订单', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageOrdersProceedsList', '收款单', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageOrdersRefundList', '退款单', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setOrderRefund', '退款单详情', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageOrdersDeliverList', '发货单', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageOrdersReturnList', '退货单', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setOrderReturn', '退货单详情', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageOrdersReceipt', '售后单据', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doOrderStatus', '处理售后单据', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setAftersale', '售后服务配置', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddAftersale', '更新售后服务配置', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAftersaleList', '售后服务列表', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageOrdersLog', '订单日志', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '订单设置', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSet', '处理订单设置', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setSendShip', '发货设置', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'UpdateOrderStatus', '更新订单状态(发货状态)', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'explortOrdersInfo', '订单导出', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'ajaxUpdateOrderItemsPrice', '更新订单明细中商品价格', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'OrderRemarkUpdate', '订单列表设置备注', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'setOrdersRemark', '设置卖家备注', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'getOrdersSearch', '订单高级搜索', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doOrderPay', '订单支付', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEditOk', '等待发货订单编辑', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '未付款订单编辑', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新未付款订单信息', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditOk', '更新等待发货订单信息', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'delItems', '删除订单商品', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'checkAudit', '订单审核', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'removeOrderItems', '订单拆分', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'autoRemoveOrderItems', '手工拆单', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'overOrder', '订单完结', 'Orders', '订单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'RefundsProperty', '退换货属性管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'specListPage', '退换货属性列表', 'RefundsProperty', '退换货属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'specEditPage', '退换货属性编辑', 'RefundsProperty', '退换货属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'specAddPage', '退换货属性添加', 'RefundsProperty', '退换货属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditSpec', '保存修改退换货属性', 'RefundsProperty', '退换货属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelSpec', '删除退换货属性', 'RefundsProperty', '退换货属性管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Delivery', '配送设置', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '配送公司列表', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增配送公司', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑配送公司', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加配送公司', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新配送公司', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除配送公司', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageListArea', '配送区域列表', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAddArea', '新增配送区域', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEditArea', '编辑配送区域', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddArea', '添加配送区域', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditArea', '更新配送区域', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelArea', '删除配送区域', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAddress', '地址库管理', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'delCityAddress', '删除地址库管理', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addCityAddress', '添加地址库管理', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'editCityAddress', '更新地址库管理', 'Delivery', '配送设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Promotions', '促销活动管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '促销活动列表', 'Promotions', '促销活动管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增促销活动', 'Promotions', '促销活动管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加促销活动', 'Promotions', '促销活动管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑促销活动', 'Promotions', '促销活动管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新促销活动', 'Promotions', '促销活动管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除促销活动', 'Promotions', '促销活动管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'ajaxDoProEdit', '启用/停用促销活动', 'Promotions', '促销活动管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Coupon', '优惠券管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '后台优惠券列表', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增优惠券', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加优惠券', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAuto', '批量新增优惠券', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAuto', '批量添加优惠劵', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除优惠券', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑优惠券', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新优惠劵', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageGetExeclCoupon', '导出优惠券', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '优惠券获取节点', 'Coupon', '优惠券管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Groupbuy', '团购活动', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '团购活动列表', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddSet', '处理团购设置', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增团购', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '保存团购', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑团购', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新团购', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除团购', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '团购设置', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageCateList', '团购类目列表', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageBrandList', '团购品牌列表', 'Groupbuy', '团购活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Members', '会员信息', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '会员列表', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'memberAdd', '新增会员', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加会员', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑会员', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新会员', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '会员删除', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doBatDelMembers', '批量删除会员', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pointList', '会员积分记录', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doBacthMembers', '批量冻结', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'feedBackList', '买家留言列表', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'replyAjax', '回复买家留言', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'explortFeedBackList', '导出买家留言', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '会员基本设置', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSet', '保存会员基本设置', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'fieldsList', '会员属性项列表', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'fieldsAdd', '会员属性项详情', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doFields', '会员属性项添加', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doFieldDel', '会员属性项删除', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addOrder', '替客户下单', 'Members', '会员管理', '1', '10', '0');
INSERT INTO `fx_role_node` SET `module`='Sourceplatform',`module_name`='会员所属平台管理',`auth_type`='1';
INSERT INTO `fx_role_node` SET `action`='pageList',`action_name`='所属平台列表',`module`='Sourceplatform',`module_name`='所属平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='pageAdd',`action_name`='添加平台',`module`='Sourceplatform',`module_name`='所属平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doAdd',`action_name`='新增平台',`module`='Sourceplatform',`module_name`='所属平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='pageEdit',`action_name`='所属平台编辑',`module`='Sourceplatform',`module_name`='所属平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doEdit',`action_name`='更新所属平台信息',`module`='Sourceplatform',`module_name`='所属平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doDel',`action_name`='删除所属平台',`module`='Sourceplatform',`module_name`='所属平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doBatDelPlat',`action_name`='批量删除所属平台',`module`='Sourceplatform',`module_name`='所属平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `module`='MembersDistributed',`module_name`='会员平台分布管理',`auth_type`='1 ';
INSERT INTO `fx_role_node` SET `action`='platformPie',`action_name`='会员平台分布饼图',`module`='MembersDistributed',`module_name`='会员平台分布管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='membersAreaPie',`action_name`='会员地区分布饼图',`module`='MembersDistributed',`module_name`='会员平台分布管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='memberThdPic',`action_name`='第三方授权登录平台分步',`module`='MembersDistributed',`module_name`='会员平台分布管理',`auth_type`='0';
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Memberlevel', '会员等级', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '会员等级列表', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增会员等级', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加会员等级', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑会员等级', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新会员等级', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除会员等级', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditLevelDefault', '设置会员等级默认值', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doBacthLevel', '批量设置等级', 'Memberlevel', '会员等级', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Membergroup', '会员分组', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '会员分组列表', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增会员分组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加会员分组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑会员分组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新会员分组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除会员分组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'groupingPage', '会员归组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSet', '添加会员归组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelSet', '删除会员归组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doBacthGroup', '批量设置分组', 'Membergroup', '会员分组', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Authorize', '分销产品授权', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '授权线管理列表', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增产品授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加产品授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑产品授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新产品授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDefault', '设置默认授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '会员授权线设置', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSet', '更新会员授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelSet', '删除会员授权线', 'Authorize', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Thdlogin', '第三方授权登录设置管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '授权登录设置页面', 'Thdlogin', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '保存第三方授权登录信息', 'Thdlogin', '分销产品授权', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Subcompany', '子公司管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '子公司列表页', 'Subcompany', '子公司管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '子公司添加页', 'Subcompany', '子公司管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '新增子公司', 'Subcompany', '子公司管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑子公司', 'Subcompany', '子公司管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '修改子公司', 'Subcompany', '子公司管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除子公司', 'Subcompany', '子公司管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'BalanceInfo', '结余款管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '结余款调整单列表', 'BalanceInfo', '结余款管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'detailBalanceInfo', '结余款调整单详情', 'BalanceInfo', '结余款管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addBalanceInfo', '新增结余款调整单', 'BalanceInfo', '结余款管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddBalanceInfo', '添加结余款调整单', 'BalanceInfo', '结余款管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'explortBalanceInfo', '导出结余款', 'BalanceInfo', '结余款管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doStatus', '审核结余款调整单', 'BalanceInfo', '结余款管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'BalanceType', '结余款类型管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '结余款类型列表', 'BalanceType', '结余款类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doStatusBalanceType', '启用/停用结余款类型', 'BalanceType', '结余款类型管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Voucher', '销货收款单管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '销货收款单列表', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addVoucher', '新增销货收款单', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '保存销货收款单', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑销货收款单', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新销货收款单', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'explortVoucher', '导出销货收款单', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doStatus', '处理审核状态', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'detailVoucher', '销货收款单详情', 'Voucher', '销货收款单管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Financial', '支付管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageListOnline', '线上支付设置 ', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageListOffline', '线下支付配置', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAddOffline', '新增线下支付表单', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddOffline', '保存线下收款帐号', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageListVerify', '线下充值审核列表', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelOffline', '删除线下支付账号', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEditOffline', '编辑线下收款帐号', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditOffline', '更新线下收款帐号', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSetOnline', '设置默认线下支付方式', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doStatusOnline', '启用线上支付方式', 'Financial', '支付管理', '1', '10', '0');
INSERT INTO `fx_role_node` SET `module`='Invoice',`module_name`='发票设置管理',`auth_type`='1';
INSERT INTO `fx_role_node` SET `action`='pageSet',`action_name`='设置发票',`module`='Invoice',`module_name`='发票设置',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doSet',`action_name`='修改发票设置',`module`='Invoice',`module_name`='发票设置',`auth_type`='0';
INSERT INTO `fx_role_node` SET `module`='IncreaseInvoice',`module_name`='增值税发票设置管理',`auth_type`='1';
INSERT INTO `fx_role_node` SET `action`='pageList',`action_name`='增值税列表',`module`='IncreaseInvoice',`module_name`='增值税发票设置',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doVerify',`action_name`='增值税发票审核',`module`='IncreaseInvoice',`module_name`='增值税发票设置',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='detailInvoiceInfo',`action_name`='增值税发票详情',`module`='IncreaseInvoice',`module_name`='增值税发票设置',`auth_type`='0';
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'System', '管理帐号', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '管理员列表', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增管理员', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加管理员', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑管理员', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新管理员', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditStatus', '启用/停用管理员账号', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelete', '删除管理员', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdminLog', '管理员登陆日志', 'System', '管理帐号', '1', '10', '0');
INSERT INTO `fx_role_node` SET `module`='Images',`module_name`='网站图片空间管理',`auth_type`='1';
INSERT INTO `fx_role_node` SET `action`='index',`action_name`='图片列表',`module`='Images',`module_name`='网站图片空间管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doDel',`action_name`='删除图片',`module`='Images',`module_name`='网站图片空间管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='pageSet',`action_name`='水印设置',`module`='Images',`module_name`='网站图片空间管理',`auth_type`='0';
INSERT INTO `fx_role_node` VALUES (NULL, 'itemImageConfig', '商品详情页显示设置', 'Images', '官网模板', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Role', '权限组管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '角色列表', 'Role', '权限组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增角色', 'Role', '权限组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加角色', 'Role', '权限组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑角色', 'Role', '权限组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新角色', 'Role', '权限组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditStatus', '角色启用/停用', 'Role', '权限组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelete', '删除角色', 'Role', '权限组管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'RoleNode', '节点管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '节点列表', 'RoleNode', '节点管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增节点', 'RoleNode', '节点管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加节点', 'RoleNode', '节点管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑节点', 'RoleNode', '节点管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新节点', 'RoleNode', '节点管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEditStatus', '节点启用/停用', 'RoleNode', '节点管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDelete', '删除节点', 'RoleNode', '节点管理', '1', '10', '0');
INSERT INTO `fx_role_node` SET `module`='Point',`module_name`='积分设置管理',`auth_type`='1';
INSERT INTO `fx_role_node` SET `action`='pageSet',`action_name`='积分设置',`module`='Point',`module_name`='积分设置管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doSet',`action_name`='修改积分设置',`module`='Point',`module_name`='积分设置管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='pointLevel',`action_name`='积分等级列表',`module`='Point',`module_name`='积分等级列表',`auth_type`='0';
INSERT INTO `fx_role_node` SET `module`='Api',`module_name`='分销开放平台管理',`auth_type`='1';
INSERT INTO `fx_role_node` SET `action`='pageSet',`action_name`='获取密钥',`module`='Api',`module_name`='分销开放平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='yunerppageSet',`action_name`='云ERP店铺授权',`module`='Api',`module_name`='分销开放平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='DoSetyunerp',`action_name`='保存云ERP店铺授权',`module`='Api',`module_name`='分销开放平台管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `module`='Consultation',`module_name`='购买咨询管理',`auth_type`='1';
INSERT INTO `fx_role_node` SET `action`='index',`action_name`='购买咨询列表',`module`='Consultation',`module_name`='购买咨询管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='pageDetail',`action_name`='购买咨询详情',`module`='Consultation',`module_name`='购买咨询管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doConsultationReply',`action_name`='回复购买咨询',`module`='Consultation',`module_name`='购买咨询管理',`auth_type`='0';
INSERT INTO `fx_role_node` SET `action`='doDel',`action_name`='删除咨询',`module`='Consultation',`module_name`='购买咨询管理',`auth_type`='0';
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Package', '数据包管理', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '数据包列表', 'Package', '数据包管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增数据包', 'Package', '数据包管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '添加数据包', 'Package', '数据包管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑数据包', 'Package', '数据包管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新数据包', 'Package', '数据包管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除数据包', 'Package', '数据包管理', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Email', '邮件设置', '1', '10', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', 'SMTP设置', 'Email', '邮件设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSetSmtp', '更新SMTP设置', 'Email', '邮件设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doTestSmtp', '发送测试邮件', 'Email', '邮件设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageTemp', '邮件模版', 'Email', '邮件设置', '1', '10', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '已发送列表', 'Email', '邮件设置', '1', '10', '0');
insert into fx_role_node set `module`='Distirbution',`module_name`='淘宝铺货',`auth_type`='1';
insert into fx_role_node set `action`='taobaoIndex',`action_name`='店铺绑定',`module`='Distirbution',`module_name`='店铺绑定',`auth_type`='0';
insert into fx_role_node set `action`='taobaoSetSynRules',`action_name`='下载淘宝商品',`module`='Distirbution',`module_name`='下载淘宝商品',`auth_type`='0';
insert into fx_role_node set `action`='deliveryTemplateList',`action_name`='物流模板列表',`module`='Distirbution',`module_name`='下载物流模板',`auth_type`='0';
insert into fx_role_node set `action`='taobaoSet',`action_name`='淘宝铺货设置',`module`='Distirbution',`module_name`='淘宝铺货设置',`auth_type`='0';
insert into fx_role_node set `action`='doDelShops',`action_name`='取消店铺授权',`module`='Distirbution',`module_name`='店铺绑定',`auth_type`='0';
insert into fx_role_node set `action`='topOauth',`action_name`='店铺授权更新',`module`='Distirbution',`module_name`='店铺绑定',`auth_type`='0';
insert into fx_role_node set `action`='doDelShopGoods',`action_name`='删除已下载淘宝商品',`module`='Distirbution',`module_name`='店铺绑定',`auth_type`='0';
insert into fx_role_node set `action`='downAllShopGoods',`action_name`='同步全部淘宝商品',`module`='Distirbution',`module_name`='店铺绑定',`auth_type`='0';
insert into fx_role_node set `action`='downShopGoods',`action_name`='批量下载淘宝商品',`module`='Distirbution',`module_name`='店铺绑定',`auth_type`='0';
insert into fx_role_node set `action`='downDeliveryTemplate',`action_name`='下载物流模板',`module`='Distirbution',`module_name`='店铺绑定',`auth_type`='0';
insert into fx_role_node set `module`='GoodsFreeRecommend',`module_name`='自由搭配管理',`auth_type`='1';
insert into fx_role_node set `action`='freeRecommendList',`action_name`='自由搭配列表',`module`='GoodsFreeRecommend',`module_name`='自由搭配管理',`auth_type`='0';
insert into fx_role_node set `action`='addFreeRecommendPage',`action_name`='新增自由搭配',`module`='GoodsFreeRecommend',`module_name`='自由搭配管理',`auth_type`='0';
insert into fx_role_node set `action`='editFreeRecommendPage',`action_name`='编辑自由搭配',`module`='GoodsFreeRecommend',`module_name`='自由搭配管理',`auth_type`='0';
insert into fx_role_node set `action`='ajaxDelFreeRecommend',`action_name`='删除自由搭配',`module`='GoodsFreeRecommend',`module_name`='自由搭配管理',`auth_type`='0';
insert into fx_role_node set `module`='Menus',`module_name`='系统菜单管理',`auth_type`='1';
insert into fx_role_node set `action`='index',`action_name`='后台菜单列表',`module`='Menus',`module_name`='返利列表',`auth_type`='0';
insert into fx_role_node set `action`='getUcenterMenus',`action_name`='会员中心菜单列表',`module`='Menus',`module_name`='返利列表',`auth_type`='0';
insert into fx_role_node set `action`='doStatusMenus',`action_name`='启用/停用菜单',`module`='Menus',`module_name`='返利列表',`auth_type`='0';
insert into fx_role_node set `module`='Spike',`module_name`='秒杀活动',`auth_type`='1';
insert into fx_role_node set `action`='index',`action_name`='秒杀列表',`module`='Spike',`module_name`='秒杀活动',`auth_type`='0';
insert into fx_role_node set `action`='add',`action_name`='新增秒杀',`module`='Spike',`module_name`='秒杀活动',`auth_type`='0';
insert into fx_role_node set `action`='pageSet',`action_name`='秒杀设置',`module`='Spike',`module_name`='秒杀活动',`auth_type`='0';
insert into fx_role_node set `action`='pageCateList',`action_name`='秒杀分类列表',`module`='Spike',`module_name`='秒杀活动',`auth_type`='0';
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Presale', '预售活动', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '预售活动列表', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAddSet', '处理预售设置', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增预售', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '保存预售', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageEdit', '编辑预售', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doEdit', '更新预售', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doDel', '删除预售', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '预售设置', 'Presale', '预售活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'PrepaidCard', '充值卡管理', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '充值卡列表', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '充值卡单个添加', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAdd', '执行充值卡单个添加', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAuto', '充值卡批量添加', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doAuto', '执行充值卡批量添加', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'isOpen', '充值卡开启、关闭', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pcServiceVerify', '充值卡客审', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pcFinanceVerify', '充值卡财审', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pcProcessingError', '充值卡驳回', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'deleteCard', '充值卡删除', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '充值卡配置', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doSet', '保存充值卡配置', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'doExcel', '充值卡导出', 'PrepaidCard', '充值卡管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Lottery', '抽奖活动', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '抽奖活动列表', 'Lottery', '抽奖活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'userList', '奖品列表', 'Lottery', '抽奖活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Sms', 'SMS管理', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSms', 'SMS设置', 'Sms', 'SMS管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '已发送列表', 'Sms', 'SMS管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageTemp', '短信模板', 'Sms', 'SMS管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '红包调整单列表', 'JlbInfo', '红包管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'addBonusInfo', '新增红包调整单', 'JlbInfo', '红包管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '红包设置', 'JlbInfo', '红包管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'Salespromotion', '分销商引荐管理', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '分销商引荐管理', 'Salespromotion', '推广销售管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'showSalesSetList', '销售额设定', 'Salespromotion', '推广销售管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'index', '商品返利设定', 'Promotings', '推广销售管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'PBStatements', '返利报表', 'Promotings', '推广销售管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '试用活动列表', 'Try', '试用活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageAdd', '新增试用活动', 'Try', '试用活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'apply_index', '试用活动申请列表', 'Try', '试用活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'report', '试用报告列表', 'Try', '试用活动', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageSet', '试用活动设置', 'Try', '试用活动', '1', '0', '0');
insert into fx_role_node set action='',action_name='',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='1';
insert into fx_role_node set action='edit',action_name='可视化编辑页面',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='0';
insert into fx_role_node set action='huifu',action_name='初始化首页',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='0';
insert into fx_role_node set action='save',action_name='保存首页',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='0';
insert into fx_role_node set action='zancun',action_name='暂存首页',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='0';
insert into fx_role_node set action='index',action_name='预览暂存首页',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='0';
insert into fx_role_node set action='huanyuan',action_name='还原上次编辑',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='0';
insert into fx_role_node set action='searchEditLog',action_name='查看编辑日志',module='Edit',module_name='可视化模块',status='1',sort='10',auth_type='0';
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'MergerPayment', '合并支付管理', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'pageList', '合并支付订单列表', 'MergerPayment', '合并支付管理', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, '', '', 'SalesStatistics', '销售统计', '1', '0', '1');
INSERT INTO `fx_role_node` VALUES (NULL, 'SalesRanking', '销售量排名', 'SalesStatistics', '销售统计', '1', '0', '0');
INSERT INTO `fx_role_node` VALUES (NULL, 'MembersRanking', '购买量排名', 'SalesStatistics', '销售统计', '1', '0', '0');
